lint:
  files_exist:
    - .github/workflows/ci.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-proteinannotator_logo_light.png
    - docs/images/nf-core-proteinannotator_logo_light.png
    - docs/images/nf-core-proteinannotator_logo_dark.png
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Olga Botvinnik
  description: Generation of sequence-level annotations for amino acid sequences
  version: 1.0.0
  force: true
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  is_nfcore: true
  name: proteinannotator
  org: nf-core
