lint:
  files_exist:
    - .github/workflows/ci.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-proteinannotator_logo_light.png
    - docs/images/nf-core-proteinannotator_logo_light.png
    - docs/images/nf-core-proteinannotator_logo_dark.png
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 4.0.0
repository_type: pipeline
template:
  author: Olga Botvinnik, Evangelos Karatzas
  description: Generation of sequence-level annotations for amino acid sequences
  force: false
  is_nfcore: true
  name: proteinannotator
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.1.0dev
