# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "functional_annotation"
description: Functional annotation of proteins
keywords:
  - annotation
  - functional
  - protein
  - diamond
  - interproscan
  - blastp

components:
  - diamond
  - interproscan
input:
  - ch_fasta:
      type: file
      description: |
        The input channel containing the fasta files
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
output:
  - diamond_tsv:
      type: file
      description: |
        Channel containing TSV files with taxonomic classification of DIAMOND hits
        Structure: [ val(meta), path(tsv) ]
      pattern: "*.{tsv,tsv.gz}"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@eweizy"
  - "@tracelail"
maintainers:
  - "@eweizy"
  - "@tracelail"
