---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "diamond"
description: Downloads NCBI RefSeq and taxonomy databases, builds a DIAMOND database, and performs protein sequence alignment using DIAMOND BLASTP
keywords:
  - alignment
  - diamond
  - blastp
  - protein
  - refseq
  - taxonomy

components:
  - ncbirefseqdownload
  - diamondpreparetaxa
  - diamond/makedb
  - diamond/blastp

input:
  - ch_fasta:
      type: file
      description: |
        The input channel containing the protein FASTA files
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"

output:
  - blast:
      type: file
      description: |
        Channel containing BLAST output files
        Structure: [ val(meta), path(blast) ]
      pattern: "*"
  - xml:
      type: file
      description: |
        Channel containing XML output files
        Structure: [ val(meta), path(xml) ]
      pattern: "*.xml"
  - txt:
      type: file
      description: |
        Channel containing TXT output files
        Structure: [ val(meta), path(txt) ]
      pattern: "*.txt"
  - daa:
      type: file
      description: |
        Channel containing DIAMOND archive output files
        Structure: [ val(meta), path(daa) ]
      pattern: "*.daa"
  - sam:
      type: file
      description: |
        Channel containing SAM alignment files
        Structure: [ val(meta), path(sam) ]
      pattern: "*.sam"
  - tsv:
      type: file
      description: |
        Channel containing TSV output files
        Structure: [ val(meta), path(tsv) ]
      pattern: "*.tsv"
  - paf:
      type: file
      description: |
        Channel containing PAF alignment files
        Structure: [ val(meta), path(paf) ]
      pattern: "*.paf"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"

authors:
  - "@tracelail"
maintainers:
  - "@tracelail"