---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "interproscan_setup"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "interproscan":
      ## TODO nf-core: Add a description and other details for the software below
      description: "InterPro integrates together predictive information about proteins function from a number of partner resources"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "https://github.com/ebi-pf-team/interproscan"
      doi: ""
      licence: ["GPL v3"]
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  #
  ## TODO nf-core: Delete / customise this example input
  - - interproscan_db:
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
        type: directory
        description: Path to the interproscan database (untarred
          http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${version_major}-${version_minor}/interproscan-${version_major}-${version_minor}-64-bit.tar.gz)
    - db_version:
        type: string
        description: Version of the interproscan database for the versions.yml

## TODO nf-core: Add a description of all of the variables used as output
output:
  - - interproscan_db_prepared:
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
        type: directory
        description: Path to the interproscan database (untarred
          http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${version_major}-${version_minor}/interproscan-${version_major}-${version_minor}-64-bit.tar.gz)
    - db_version:
        type: string
        description: Version of the interproscan database for the versions.yml

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@olgabot"
maintainers:
  - "@olgabot"
